[package]
name = "dotso"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
phper = "0.12.0"
reqwest = { version = "0.11.22", features = ["blocking", "cookies"] }
thiserror = "1.0.50"
